import InfoLayout from "@/components/InfoLayout";

const sections = [
  { title: "1. Information We Collect", body: "We collect information you provide directly (name, email, country, government ID where required), information generated by your use of the platform (transaction history, login timestamps, device information), and information from third-party identity verification partners where applicable." },
  { title: "2. How We Use Your Information", body: "We use your information to operate and improve our services, verify your identity and prevent fraud, comply with applicable law and regulatory obligations, communicate with you about your account, and personalise your banking experience." },
  { title: "3. How We Share Your Information", body: "We do not sell your personal information. We share data only with: financial infrastructure partners necessary to process your transactions; regulatory and law enforcement bodies when legally required; and service providers bound by confidentiality obligations who assist us in operating the platform." },
  { title: "4. Data Retention", body: "We retain your information for as long as your account is active and for a period thereafter as required by applicable financial regulations (typically 7 years). You may request deletion of non-legally required data by contacting support@interzenexmicrofinance.online." },
  { title: "5. Security", body: "All personal information is encrypted at rest (AES-256) and in transit (TLS 1.3+). Access is restricted to authorised personnel on a need-to-know basis, and all access is logged and audited." },
  { title: "6. Your Rights", body: "Depending on your jurisdiction, you may have the right to access, correct, delete, or port your personal data, and to object to or restrict certain processing. To exercise your rights, contact support@interzenexmicrofinance.online." },
  { title: "7. Cookies", body: "We use essential session cookies to keep you logged in, and analytics cookies to understand how our platform is used. No advertising cookies are deployed. See our Cookie Policy for details." },
  { title: "8. Contact", body: "For privacy questions or data-subject requests, contact our Data Protection Officer at privacy@interzenexmicrofinance.online." },
];

export default function PrivacyPage() {
  return (
    <InfoLayout title="Privacy Policy" subtitle={`Last updated: June 2026`}>
      <div className="space-y-5">
        <div className="glass rounded-2xl p-6">
          <p className="text-slate-400 leading-relaxed text-sm">
            Interzenex Microfinance (&quot;we&quot;, &quot;us&quot;, or &quot;our&quot;) is committed to protecting your personal
            information. This Privacy Policy explains what data we collect, how we use it, and your
            rights in relation to it. By using interzenexmicrofinance.online you agree to the
            practices described in this policy.
          </p>
        </div>
        {sections.map((s) => (
          <div key={s.title} className="glass rounded-2xl p-6">
            <h2 className="text-base font-semibold text-slate-100 mb-3">{s.title}</h2>
            <p className="text-sm text-slate-400 leading-relaxed">{s.body}</p>
          </div>
        ))}
      </div>
    </InfoLayout>
  );
}
